# https://open.kattis.com/problems/hailstone2
# 1s
# 1.8 Easy

# This was generated by GPT4 by porting my Prolog program
# (after several prompts to make it as short as possible).
# $><<->n{n<2?1:1+self[n%2<1?n/2:3*n+1]}[gets.to_i] # Does not work

# Also by GOT4: This actually works!
# 56 chars: Top 10 place 3! (Thanks, GPT4!)
# puts (f=->n{n<2?1:1+f[n%2<1?n/2:3*n+1]}).call(gets.to_i)

# And then I make some improvements:
# 50 chars. Top 10 place 2
$><<(f=->n{n<2?1:1+f[n%2<1?n/2:3*n+1]})[gets.to_i]
