/* 

  Euler #45 in JavaScript.

  Problem 45:
  """  
  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
  Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
  Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

  It can be verified that T(285) = P(165) = H(143) = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
  """


  This JavaScript program was created by Hakan Kjellerstrand, hakank@gmail.com
  See also my JavaScript page: http://www.hakank.org/javascript/

*/

'use strict';
const {timing2} = require('./js_utils.js');

var pent = function(n) { return Math.floor(n*(3*n-1) / 2); }
var tri  = function(n) { return Math.floor(n*(n+1) / 2);   }
var hex  = function(n) { return n*(2*n-1);                 }


// 5ms
var euler45a = function() {
    var t = 285+1;
    var tt = tri(t);
    var p = 165;
    var pp = pent(p);
    var h = 143;
    var hh = hex(h);
    while (tt !== pp || pp !== hh)  {
        t++;
        tt = tri(t);
        if (tt > pp) { p++; pp = pent(p); }
        if (pp > hh) { h++; hh = hex(h);  }
        if (tt > hh) { h++; hh = hex(h);  }
    }
    
    return tt;
}

timing2(euler45a); // 5ms
