%% From Atom example nextto.pl
%% hakank: renamed nextto/3 to nexttox/3.


%% Positive examples
pos(nexttox(e, a, [e,a])).
pos(nexttox(a, e, [a,a,e,e])).
pos(nexttox(e, c, [a,e,c])).
pos(nexttox(a, c, [b,a,c,a])).
pos(nexttox(e, e, [e,e,d])).
pos(nexttox(d, b, [d,b,c])).
pos(nexttox(b, d, [a,c,b,b,d,e,a,c,a,c,b])).
pos(nexttox(a, d, [c,a,d])).
pos(nexttox(a, c, [d,a,c])).
pos(nexttox(a, d, [a,a,d,d,d])).
pos(nexttox(c, d, [b,c,d])).
pos(nexttox(a, a, [b,c,a,a,c,d])).
pos(nexttox(e, b, [a,e,b])).
pos(nexttox(e, e, [a,c,c,e,e,e,c])).
pos(nexttox(a, c, [a,c])).
pos(nexttox(e, d, [c,c,e,d,e,d,b,e,a])).
pos(nexttox(a, b, [a,b])).
pos(nexttox(e, b, [e,b])).
pos(nexttox(e, b, [e,b,c])).
pos(nexttox(d, d, [d,d,b])).
pos(nexttox(c, c, [c,c])).
pos(nexttox(c, a, [d,e,e,c,a,e,a,d])).
pos(nexttox(c, e, [c,e,b,d,a,a,b])).
pos(nexttox(e, c, [a,e,c,a])).
pos(nexttox(e, e, [a,b,e,e])).
pos(nexttox(a, e, [a,e])).
pos(nexttox(d, a, [b,d,e,d,e,c,c,d,d,a,e,a,b,b])).
pos(nexttox(c, d, [c,c,d,e,e])).
pos(nexttox(e, d, [d,e,d,a])).
pos(nexttox(e, e, [e,e,b,e,e])).
pos(nexttox(a, c, [c,d,a,c])).
pos(nexttox(b, d, [b,d,c])).
pos(nexttox(d, e, [d,e,e,c])).
pos(nexttox(d, a, [d,a])).
pos(nexttox(e, d, [b,a,e,d])).
pos(nexttox(d, a, [d,a,b])).
pos(nexttox(d, b, [d,b])).
pos(nexttox(d, d, [c,d,d,e,b])).
pos(nexttox(d, a, [c,d,a,b,c,d])).
pos(nexttox(a, d, [b,a,d])).
pos(nexttox(c, b, [c,b])).
pos(nexttox(c, d, [c,d,c])).
pos(nexttox(c, b, [b,a,c,b,b])).
pos(nexttox(c, a, [c,a,b,a])).
pos(nexttox(d, d, [e,c,c,c,d,d,a,d,c])).
pos(nexttox(a, a, [d,a,a])).
pos(nexttox(a, c, [a,c,a,e,d,c,c,c])).
pos(nexttox(b, d, [a,b,d,d,d,e])).
pos(nexttox(c, d, [d,d,c,c,d])).
pos(nexttox(a, c, [e,b,b,d,b,d,a,a,c])).
pos(nexttox(b, d, [b,d])).
pos(nexttox(d, e, [a,a,e,d,e])).
pos(nexttox(d, d, [d,d])).
pos(nexttox(e, e, [a,e,e,e])).
pos(nexttox(e, c, [c,e,c,d,c,b])).
pos(nexttox(e, e, [e,e])).
pos(nexttox(e, c, [e,c])).
pos(nexttox(b, b, [b,b,b])).
pos(nexttox(b, c, [b,c,a,d,a,c])).
pos(nexttox(b, c, [e,a,c,b,c,b])).
pos(nexttox(e, d, [e,d,a,c,a,b,d,e])).
pos(nexttox(b, a, [b,a,a,c,a])).
pos(nexttox(e, e, [d,d,e,e,d])).
pos(nexttox(a, d, [a,d])).
pos(nexttox(b, b, [a,b,b])).
pos(nexttox(e, b, [d,e,b,a])).
pos(nexttox(a, e, [a,a,b,a,e,a,b,e,e])).
pos(nexttox(e, b, [d,e,e,b,b,c,c])).
pos(nexttox(e, c, [c,e,c,e])).
pos(nexttox(e, d, [e,d])).
pos(nexttox(c, d, [c,d,d,d,c,e,e,d,d,d])).
pos(nexttox(d, d, [d,d,a,b,d,e,a])).
pos(nexttox(b, a, [e,a,d,b,a])).
pos(nexttox(d, d, [d,d,c])).
pos(nexttox(c, a, [c,a])).
pos(nexttox(c, d, [c,d])).
pos(nexttox(e, d, [c,a,e,d,b,a,a,c])).
pos(nexttox(b, e, [b,e])).
pos(nexttox(a, a, [a,a])).
pos(nexttox(b, d, [b,b,b,d,a])).
pos(nexttox(c, b, [e,c,b])).
pos(nexttox(e, e, [a,b,e,e,b,a])).
pos(nexttox(c, a, [d,c,a,e])).
pos(nexttox(a, b, [c,c,a,b,d])).
pos(nexttox(b, b, [b,b,c])).
pos(nexttox(b, d, [e,d,b,d,a])).
pos(nexttox(d, c, [d,c])).
pos(nexttox(c, d, [c,d,d,e,c,a,a])).
pos(nexttox(c, b, [c,b,c,a])).
pos(nexttox(c, b, [e,d,a,d,c,b,c,c,b,a,e,b,e])).
pos(nexttox(c, a, [e,e,c,a])).
pos(nexttox(a, c, [a,a,c])).
pos(nexttox(b, c, [b,c])).
pos(nexttox(a, b, [a,b,a,b,d])).
pos(nexttox(a, d, [e,e,d,a,d,e])).
pos(nexttox(e, b, [e,d,a,e,b])).
pos(nexttox(d, b, [d,b,c,a,a])).
pos(nexttox(d, d, [c,c,d,d])).
pos(nexttox(e, d, [e,d,c,d,c,e,b])).
pos(nexttox(c, b, [d,c,b])).

%% Negative examples
neg(nexttox(e, e, [e,b,e])).
neg(nexttox(b, d, [])).
neg(nexttox(c, d, [a,b,d,e])).
neg(nexttox(a, e, [])).
neg(nexttox(e, d, [c,a])).
neg(nexttox(c, d, [])).
neg(nexttox(b, b, [b])).
neg(nexttox(e, e, [e])).
neg(nexttox(b, b, [b,c])).
neg(nexttox(b, c, [a,e])).
neg(nexttox(e, b, [b])).
neg(nexttox(a, b, [e])).
neg(nexttox(a, d, [c,d,e])).
neg(nexttox(a, c, [d,e,b])).
neg(nexttox(c, c, [a])).
neg(nexttox(c, a, [b,d,d])).
neg(nexttox(b, e, [c,a])).
neg(nexttox(a, e, [a])).
neg(nexttox(b, e, [b,d,a,c])).
neg(nexttox(b, b, [])).
neg(nexttox(e, c, [])).
neg(nexttox(e, b, [])).
neg(nexttox(e, a, [d])).
neg(nexttox(e, b, [d,a])).
neg(nexttox(a, c, [c])).
neg(nexttox(a, e, [e])).
neg(nexttox(d, d, [])).
neg(nexttox(a, b, [b,b,b])).
neg(nexttox(a, b, [a])).
neg(nexttox(e, a, [b,c])).
neg(nexttox(e, d, [])).
neg(nexttox(b, c, [b,b])).
neg(nexttox(c, b, [b])).
neg(nexttox(b, d, [d,d])).
neg(nexttox(a, d, [a,e])).
neg(nexttox(e, c, [d,a])).
neg(nexttox(e, e, [c])).
neg(nexttox(c, b, [d,a,a,d,d])).
neg(nexttox(a, a, [b,d])).
neg(nexttox(a, d, [b,c])).
neg(nexttox(b, e, [a,b])).
neg(nexttox(b, d, [d])).
neg(nexttox(b, e, [c])).
neg(nexttox(d, c, [])).
neg(nexttox(a, c, [b])).
neg(nexttox(d, a, [e,e])).
neg(nexttox(c, e, [e])).
neg(nexttox(a, c, [e,c])).
neg(nexttox(b, b, [c])).
neg(nexttox(e, a, [d,b])).
neg(nexttox(e, c, [d,d,d,a,c,d])).
neg(nexttox(c, d, [c])).
neg(nexttox(e, c, [e])).
neg(nexttox(c, d, [e])).
neg(nexttox(d, e, [])).
neg(nexttox(e, b, [e])).
neg(nexttox(a, c, [b,b,a,b,d,c,d])).
neg(nexttox(c, a, [a,a])).
neg(nexttox(c, a, [c])).
neg(nexttox(e, d, [b])).
neg(nexttox(e, c, [a])).
neg(nexttox(e, e, [a,a,c,d,e,d,b])).
neg(nexttox(a, c, [])).
neg(nexttox(a, e, [c,d,e])).
neg(nexttox(d, e, [b,b,c])).
neg(nexttox(d, e, [c])).
neg(nexttox(d, b, [d,a])).
neg(nexttox(d, d, [a,a,e])).
neg(nexttox(b, b, [a,e,b,d,c,c])).
neg(nexttox(e, c, [c,c,d,b,e])).
neg(nexttox(a, e, [c])).
neg(nexttox(b, a, [])).
neg(nexttox(d, c, [b])).
neg(nexttox(c, c, [])).
neg(nexttox(a, e, [a,b])).
neg(nexttox(d, b, [])).
neg(nexttox(b, a, [a,e])).
neg(nexttox(d, a, [])).
neg(nexttox(c, e, [])).
neg(nexttox(b, e, [])).
neg(nexttox(b, e, [c,d])).
neg(nexttox(b, c, [])).
neg(nexttox(d, e, [d,c])).
neg(nexttox(a, c, [e,b,e])).
neg(nexttox(b, a, [b,b,d])).
neg(nexttox(c, d, [c,e])).
neg(nexttox(a, b, [a,e,b,a])).
neg(nexttox(d, c, [b,e,d])).
neg(nexttox(c, a, [])).
neg(nexttox(a, e, [b,e,e])).
neg(nexttox(a, d, [])).
neg(nexttox(e, a, [])).
neg(nexttox(b, b, [b,d,c,e,a,c,e,a,a,a,e,c,c,e,b])).
neg(nexttox(c, b, [d,a])).
neg(nexttox(d, e, [a,e])).
neg(nexttox(e, a, [a])).
neg(nexttox(d, d, [e,a,a])).
neg(nexttox(a, b, [])).
neg(nexttox(d, a, [b])).
neg(nexttox(b, e, [a])).
