#|
  Euler #12 in Racket

  Problem 12
  """
  The sequence of triangle numbers is generated by adding the natural numbers. 
  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
  The first ten terms would be:

  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

       1: 1
       3: 1,3
       6: 1,2,3,6
      10: 1,2,5,10
      15: 1,3,5,15
      21: 1,3,7,21
      28: 1,2,4,7,14,28

  We can see that the 7th triangle number, 28, is the first triangle number 
  to have over five divisors.

  Which is the first triangle number to have over five-hundred divisors?")
  """

  This Racket program was created by Hakan Kjellerstrand, hakank@gmail.com
  See also my Racket page: http://www.hakank.org/racket/

|#

#lang racket

(provide (all-defined-out))

(require math/number-theory)

(require "utils_hakank.rkt")

;;; Already defined in the math package
;; (define (triangle-number n)
;;   (for/sum ([i (range 1 (add1 n))])
;;     i)
;;   )

;;; Not too bad
;;; cpu time: 440 real time: 441 gc time: 26
(define (euler12a)
  (for/first ([n (in-naturals)]
              #:when (> (length (divisors (triangle-number n))) 500))
    (triangle-number n)
  ))

;;; A little faster:
;;; cpu time: 278 real time: 278 gc time: 24
(define (euler12b)
  (let ([tnum 0])
    (for/first ([n (in-naturals 1)]
                #:do [(set! tnum (+ tnum n))]
                #:when (> (length (divisors tnum)) 500))
      tnum)
    )
  )

(define (run)
  ;;; (time-function euler12a)
  (time-function euler12b)
  )

(run)



