#=
  Changepoint detection
  From https://nishanthu.github.io/articles/ChangePointAnalysis.html

  See ~/jags/change_point.R
  The JAGS model
  model {
     for (i in 1:N) {
       mu0[i] = ifelse(i < cp, mu1, mu2)
       x[i] ~ dnorm(mu0[i], 1)
     }
     mu1 ~ dunif(0, mu)
     mu2 ~ dunif(mu, 10*mu)
     cp ~ dunif(0, N)
   }
"""
out$cp %>% as.vector %>% mean %>% round(1)
[1] 13.5
"""

   Compare with
     - changepoint_coal_miners.jl
     - changepoint_text_messages.jl

=#

# using Memoization
using Turing, StatsPlots, DataFrames
using ReverseDiff, Zygote, Tracker
using Printf
# Turing.setadbackend(:reversediff)
# Turing.setadbackend(:zygote)
# Turing.setadbackend(:tracker)

include("jl_utils.jl")


@model function changepoint(ys)
    N = length(ys)
    mu = mean(ys)

    mu1 ~ Uniform(0, mu)
    mu2 ~ Uniform(mu, 10*mu)
    cp ~ DiscreteUniform(1,N)

    for i in 1:N
        ys[i] ~ i < cp ? Normal(mu1,1) : Normal(mu2,1)
    end

end

# Generated by R:
# > c(rnorm(13, mean=0, sd=0.5), rnorm(20, mean=4, sd=0.5))
# ys = [0.90685440,0.38219559,0.13508408,-0.96054590,0.78553871,0.06791336,-0.09750806,-0.85431057,
#      0.33478539,0.76388689,0.52911522,-0.41226421,1.53302740,
#      5.01118838,4.75164473,3.79149212,3.97544567,4.33985561,4.52511631,4.21723600,
#      4.22733898,3.80925885,3.65504091,3.25267865,3.85339052,3.40136529,4.21462117,
#      3.94033196,4.00900359,4.44148942,4.23449516,4.52032000,4.41335270];

# But we use Julia here...
# Note:
#  - cp should be 14
#  - mu1 should be 0
#  - mu2 should be 4
ys = vcat(rand(Normal(0,0.5),13), rand(Normal(4,0.5),20) )

# Larger instance (130 + 200 elements)
# cp: 131
# mu1: 1
# mu2: 14
# ys = vcat(rand(Normal(1,0.5),130), rand(Normal(14,0.5),200) )

model = changepoint(ys)

num_chains = 4

# chains = sample(model, Prior(), MCMCThreads(), 40_000, num_chains)

# chains = sample(model, MH(), MCMCThreads(), 40_000, num_chains)
chains = sample(model, MH(), 100_000)


# chains = sample(model, SMC(), 10_000)
# chains = sample(model, PG(20), 1_000)

display(chains[[:cp,:mu1,:mu2]]) # We are not interested in :ys

show_var_dist_pct(chains, :cp)
show_var_dist_pct(chains, :mu1)
show_var_dist_pct(chains, :mu2)
