#=

  Euler #45 in Julia.

  Problem 45:
  """
  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
  Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
  Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

  It can be verified that T(285) = P(165) = H(143) = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
  """

  This Julia program was created by Hakan Kjellerstrand, hakank@gmail.com
  See also my Julia page: http://www.hakank.org/julia/

=#

include("Euler.jl")

pent(n) = floor(Int, n*(3*n-1) / 2)
tri(n) = floor(Int, n*(n+1) / 2)
hex(n) = n*(2*n-1)

# 0.00013708s
function euler45a()
    t = 285+1
    tt = tri(t)
    p = 165
    pp = pent(p)
    h = 143
    hh = hex(h)
    while tt != pp || pp != hh
        t += 1
        tt = tri(t)
        if tt > pp p+=1; pp = pent(p) end
        if pp > hh h+=1; hh = hex(h) end
        if tt > hh h+=1; hh = hex(h) end
    end

    return tt
end

run_euler(euler45a)
