#!/usr/local/bin/perl
# 
# Thu Jun 21 07:21:51 2012/hakank@bonetmail.com
# 
# Make random strengths array for picking_teams.mzn
# 
$|=1;
use strict;
use Data::Dumper;



my $n = $ARGV[0] || 100;
my $max = $ARGV[1] || 100;

my @s = ();
for (1..$n) {
  push @s, int(rand($max));
}

my $s_str =  join ", ", @s;
my $date = scalar localtime;
print<<EOT;
%
% Data for picking_teams.mzn 
% Generated by picking_teams_generate.pl $n $max
% ($date)
% 
%
%
n = $n;
s = [$s_str];

EOT
